v5 (#9)
* push up some prelim tests

* push up some prelim tests 2

* push up some prelim tests 3

* first pass on only emulate if needed

* arch mismatch tests

* arch mismatch tests 2

* arch mismatch tests 3

* arm native test

* arm native test 2

* readme

* release tag

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: "Pkg Action"
-description: "A GitHub Action for 'compiling' node projects into binaries using vercel/pkg."
+description: "A GitHub Action for 'compiling' node projects into binaries using vercel/pkg or equivalent"
 branding:
   color: purple
   icon: package
@@ -13,7 +13,7 @@ inputs:
   arch:
     description: "The architecture to build for x64|amd64|aarch64|arm64"
     required: false
-    default: amd64
+    default: ${{ runner.arch }}
   config:
     description: "The config file to use"
     required: false
@@ -21,7 +21,7 @@ inputs:
   node-version:
     description: "The node version to package with"
     required: false
-    default: 16
+    default: "20"
   options:
     description: "Additional options and flags to pass into pkg"
     required: false
@@ -30,9 +30,9 @@ inputs:
     required: false
     default: ${{ runner.os }}
   pkg:
-    description: "The version on @vercel/pkg to use"
+    description: "The version of pkg to use"
     required: false
-    default: "pkg@5.8.1"
+    default: "@yao-pkg/pkg@5.11.5"
   test:
     description: "Hidden flag for input testing"
     default: false
@@ -78,8 +78,28 @@ runs:
           echo "target-os=${{ inputs.os }}" >> $GITHUB_OUTPUT
         fi
 
-        if [ "${{ inputs.arch }}" == "amd64" ]; then
+        if [ "${{ runner.arch }}" == "X86" ]; then
+          echo "runner-arch=x64" >> $GITHUB_OUTPUT
+        elif [ "${{ runner.arch }}" == "X64" ]; then
+          echo "runner-arch=x64" >> $GITHUB_OUTPUT
+        elif [ "${{ runner.arch }}" == "ARM" ]; then
+          echo "runner-arch=arm64" >> $GITHUB_OUTPUT
+        elif [ "${{ runner.arch }}" == "ARM64" ]; then
+          echo "runner-arch=arm64" >> $GITHUB_OUTPUT
+        else
+          echo "runner-arch=${{ runner.arch }}" >> $GITHUB_OUTPUT
+        fi
+
+        if [ "${{ inputs.arch }}" == "X86" ]; then
           echo "target-arch=x64" >> $GITHUB_OUTPUT
+        elif [ "${{ inputs.arch }}" == "X64" ]; then
+          echo "target-arch=x64" >> $GITHUB_OUTPUT
+        elif [ "${{ inputs.arch }}" == "amd64" ]; then
+          echo "target-arch=x64" >> $GITHUB_OUTPUT
+        elif [ "${{ inputs.arch }}" == "ARM" ]; then
+          echo "target-arch=arm64" >> $GITHUB_OUTPUT
+        elif [ "${{ inputs.arch }}" == "ARM64" ]; then
+          echo "target-arch=arm64" >> $GITHUB_OUTPUT
         elif [ "${{ inputs.arch }}" == "aarch64" ]; then
           echo "target-arch=arm64" >> $GITHUB_OUTPUT
         else
@@ -88,6 +108,16 @@ runs:
 
         echo "target-node=node${{ inputs.node-version }}" >> $GITHUB_OUTPUT
         echo "::endgroup::"
+
+    - name: Validate arch emulation requirements
+      shell: bash
+      run: |
+        if [ "${{ steps.pkg-action-internal.outputs.target-arch }}" != "${{ steps.pkg-action-internal.outputs.runner-arch }}" ]; then
+          if [ "${{ runner.os }}" != "Linux" ]; then
+            echo "::error title=Emulation only possible on Linux!::Emulating ${{ steps.pkg-action-internal.outputs.target-arch }} is only possible on Linux runners!"
+            exit 48
+          fi
+        fi
 
     - name: Install node ${{ inputs.node-version }}
       uses: actions/setup-node@v3
@@ -119,8 +149,8 @@ runs:
         echo "artifact-key=${{ github.event.repository.name }}-${{ steps.pkg-action-internal.outputs.target-node }}-${{ steps.pkg-action-internal.outputs.target-os }}-${{ steps.pkg-action-internal.outputs.target-arch }}-${{ github.sha }}" >> $GITHUB_OUTPUT
         echo "::endgroup::"
 
-    - name: Run x64 pkg command
-      if: inputs.test != 'true' && steps.pkg-action-internal.outputs.target-arch == 'x64'
+    - name: Run native ${{ steps.pkg-action-internal.outputs.target-arch }} pkg command
+      if: inputs.test != 'true' && steps.pkg-action-internal.outputs.target-arch == steps.pkg-action-internal.outputs.runner-arch
       shell: bash
       env:
         RUNNER_DEBUG: ${{ env.RUNNER_DEBUG }}
@@ -143,8 +173,8 @@ runs:
         fi
         stat ${{ steps.pkg-action.outputs.file }}
 
-    - name: Run arm64 pkg command
-      if: inputs.test != 'true' && steps.pkg-action-internal.outputs.target-arch == 'arm64'
+    - name: Run emulated ${{ steps.pkg-action-internal.outputs.target-arch }} pkg command
+      if: inputs.test != 'true' && steps.pkg-action-internal.outputs.target-arch == 'arm64' && steps.pkg-action-internal.outputs.runner-arch == 'x64'
       uses: uraimo/run-on-arch-action@v2
       with:
         arch: aarch64
